# set(PARTNO atmega328p)
set(PARTNO atmega168)
set(F_CPU 16000000)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_C_FLAGS "-mmcu=${PARTNO} -Wall -DF_CPU=${F_CPU} -Os -Wl,-Map=bin/${PROJECT_NAME}.map")
set(CMAKE_EXECUTABLE_SUFFIX ".elf")
set(AVROBJ avr-objcopy)
set(AVROBJ_FLAGS -O ihex -j .text -j .data)
set(CONFIG arduino)
set(AVR_DUDE avrdude)
set(AVR_DUDE_CONF /etc/avrdude.conf)
set(PORT /dev/ttyUSB0)
set(BAUD_RATE 19200)
set(AVR_DUDE_FLAGS -v -p ${PARTNO} -c ${CONFIG} -P ${PORT} -b ${BAUD_RATE} -C ${AVR_DUDE_CONF} -D -U)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
